name: mito-overview
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - matplotlib
  - numpy
  - pandas
  - pysam
  - requests
  - samtools
  - minimap2
  - bwa
  - pip
  - pip:
      - pytest
