"""Small compatibility helpers for stable public TSV contracts."""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd


MODULE_STATES = frozenset(
    {
        "ok",
        "not_configured",
        "not_applicable",
        "not_evaluable",
        "unavailable",
        "failed",
    }
)
CANONICAL_BASES = frozenset({"A", "C", "G", "T"})


def _strict_numeric_column(
    frame: pd.DataFrame,
    column: str,
    *,
    table_name: str,
    integer: bool = False,
    minimum: float | None = None,
    maximum: float | None = None,
) -> pd.Series:
    """Return one complete finite numeric column or reject the table."""

    values = pd.to_numeric(frame[column], errors="coerce")
    numeric = values.to_numpy(dtype=float)
    valid = np.isfinite(numeric)
    if integer:
        with np.errstate(invalid="ignore"):
            valid &= numeric == np.floor(numeric)
    if minimum is not None:
        valid &= numeric >= minimum
    if maximum is not None:
        valid &= numeric <= maximum
    if not bool(valid.all()):
        raise ValueError(
            f"{table_name} column {column!r} contains missing, non-finite, "
            "fractional, or out-of-domain values"
        )
    return values.astype("int64" if integer else "float64")


def validate_variant_key_table(
    frame: pd.DataFrame,
    *,
    table_name: str,
    mt_length: int | None = None,
    reference_sequence: str | None = None,
) -> pd.DataFrame:
    """Validate canonical one-based SNV keys without silently coercing rows."""

    normalized = frame.copy()
    required = {"position", "ref_base", "alt_base"}
    missing = sorted(required - set(normalized.columns))
    if missing:
        raise ValueError(f"{table_name} lacks required columns: {','.join(missing)}")
    if normalized.empty:
        return normalized

    normalized["position"] = _strict_numeric_column(
        normalized,
        "position",
        table_name=table_name,
        integer=True,
        minimum=1,
        maximum=mt_length,
    )
    for column in ("ref_base", "alt_base"):
        normalized[column] = normalized[column].astype(str).str.strip().str.upper()
        if not normalized[column].isin(CANONICAL_BASES).all():
            raise ValueError(f"{table_name} column {column!r} must contain canonical SNV bases")
    if (normalized["ref_base"] == normalized["alt_base"]).any():
        raise ValueError(f"{table_name} contains REF-equal-ALT rows")

    if reference_sequence is not None:
        reference_sequence = str(reference_sequence).upper()
        if mt_length is not None and len(reference_sequence) != mt_length:
            raise ValueError(
                f"{table_name} reference length mismatch: "
                f"expected {mt_length}, observed {len(reference_sequence)}"
            )
        expected_ref = normalized["position"].map(
            lambda position: reference_sequence[int(position) - 1]
        )
        if not (normalized["ref_base"] == expected_ref).all():
            raise ValueError(f"{table_name} REF alleles disagree with the configured reference")
    return normalized


def validate_candidate_table(
    frame: pd.DataFrame,
    *,
    table_name: str = "candidate table",
    mt_length: int | None = None,
    reference_sequence: str | None = None,
) -> pd.DataFrame:
    """Validate the internal alternate-allele candidate evidence contract.

    Candidate tables are generated by the shared allele counter. Downstream
    modules must reject malformed internal evidence rather than truncate,
    filter, or reinterpret it as a valid candidate set.
    """

    normalized = frame.copy()
    required = {
        "position",
        "ref_base",
        "alt_base",
        "depth",
        "callable_depth",
        "alt_count",
        "alt_allele_fraction",
        "heteroplasmy_fraction",
        "alt_forward",
        "alt_reverse",
        "A",
        "C",
        "G",
        "T",
    }
    missing = sorted(required - set(normalized.columns))
    if missing:
        raise ValueError(f"{table_name} lacks required columns: {','.join(missing)}")
    if normalized.empty:
        return normalized

    normalized = validate_variant_key_table(
        normalized,
        table_name=table_name,
        mt_length=mt_length,
        reference_sequence=reference_sequence,
    )
    if normalized.duplicated(subset=["position", "ref_base", "alt_base"]).any():
        raise ValueError(f"{table_name} contains duplicate variant keys")
    if normalized.duplicated(subset=["position"]).any():
        raise ValueError(f"{table_name} contains more than one alternate allele per position")

    normalized["depth"] = _strict_numeric_column(
        normalized, "depth", table_name=table_name, integer=True, minimum=1
    )
    normalized["callable_depth"] = _strict_numeric_column(
        normalized,
        "callable_depth",
        table_name=table_name,
        integer=True,
        minimum=1,
    )
    if not (normalized["depth"] == normalized["callable_depth"]).all():
        raise ValueError(f"{table_name} depth conflicts with callable_depth")
    normalized["alt_allele_fraction"] = _strict_numeric_column(
        normalized,
        "alt_allele_fraction",
        table_name=table_name,
        minimum=0,
        maximum=1,
    )
    normalized["heteroplasmy_fraction"] = _strict_numeric_column(
        normalized,
        "heteroplasmy_fraction",
        table_name=table_name,
        minimum=0,
        maximum=1,
    )
    if not np.isclose(
        normalized["alt_allele_fraction"],
        normalized["heteroplasmy_fraction"],
        rtol=0,
        atol=1e-9,
    ).all():
        raise ValueError(f"{table_name} alternate-fraction aliases conflict")

    normalized["alt_count"] = _strict_numeric_column(
        normalized,
        "alt_count",
        table_name=table_name,
        integer=True,
        minimum=1,
    )
    if (normalized["alt_count"] > normalized["callable_depth"]).any():
        raise ValueError(f"{table_name} alt_count exceeds callable_depth")
    expected_fraction = normalized["alt_count"] / normalized["callable_depth"]
    if not np.isclose(
        normalized["alt_allele_fraction"],
        expected_fraction,
        rtol=0,
        atol=5.1e-7,
    ).all():
        raise ValueError(f"{table_name} alternate fraction conflicts with allele counts")

    for column in ("alt_forward", "alt_reverse"):
        normalized[column] = _strict_numeric_column(
            normalized,
            column,
            table_name=table_name,
            integer=True,
            minimum=0,
        )
    if not (
        normalized["alt_count"]
        == normalized["alt_forward"] + normalized["alt_reverse"]
    ).all():
        raise ValueError(f"{table_name} strand counts do not sum to alt_count")

    base_columns = ["A", "C", "G", "T"]
    for column in base_columns:
        normalized[column] = _strict_numeric_column(
            normalized,
            column,
            table_name=table_name,
            integer=True,
            minimum=0,
        )
    if not (normalized[base_columns].sum(axis=1) == normalized["callable_depth"]).all():
        raise ValueError(f"{table_name} A/C/G/T counts do not sum to callable_depth")
    observed_alt = normalized.apply(
        lambda row: row[str(row["alt_base"])], axis=1
    ).astype("int64")
    if not (observed_alt == normalized["alt_count"]).all():
        raise ValueError(f"{table_name} alt_count disagrees with the alternate-base count")
    return normalized


def ensure_alt_fraction_columns(frame: pd.DataFrame) -> pd.DataFrame:
    """Return a copy with canonical and deprecated alternate-fraction columns.

    ``alt_allele_fraction`` is canonical from v0.3.0. The historical
    ``heteroplasmy_fraction`` alias remains available throughout the 0.x series.
    When both are present, disagreement is an error rather than a silent choice.
    """

    normalized = frame.copy()
    canonical = "alt_allele_fraction"
    legacy = "heteroplasmy_fraction"
    if canonical not in normalized.columns and legacy in normalized.columns:
        normalized[canonical] = normalized[legacy]
    if legacy not in normalized.columns and canonical in normalized.columns:
        normalized[legacy] = normalized[canonical]
    if canonical in normalized.columns and legacy in normalized.columns:
        canonical_values = pd.to_numeric(normalized[canonical], errors="coerce")
        legacy_values = pd.to_numeric(normalized[legacy], errors="coerce")
        comparable = canonical_values.notna() & legacy_values.notna()
        if comparable.any() and not (
            (canonical_values.loc[comparable] - legacy_values.loc[comparable]).abs() <= 1e-9
        ).all():
            raise ValueError("alt_allele_fraction conflicts with heteroplasmy_fraction")
    return normalized


def validate_module_state(status: str) -> str:
    """Validate and return one controlled module state."""

    if status not in MODULE_STATES:
        allowed = ", ".join(sorted(MODULE_STATES))
        raise ValueError(f"Unsupported module state {status!r}; expected one of: {allowed}")
    return status


def load_metric_module_state(
    path: str | Path,
    *,
    module_name: str,
    missing_status: str = "not_evaluable",
) -> tuple[str, str]:
    """Read one metric/value module summary without inventing evidence."""

    path = Path(path)
    missing_status = validate_module_state(missing_status)
    if not path.is_file():
        return missing_status, f"{module_name}_summary_missing"
    try:
        frame = pd.read_csv(path, sep="\t")
    except (OSError, pd.errors.EmptyDataError, pd.errors.ParserError):
        return "not_evaluable", f"{module_name}_summary_unusable"
    if frame.empty or not {"metric", "value"}.issubset(frame.columns):
        return "not_evaluable", f"{module_name}_summary_unusable"

    status_values = frame.loc[frame["metric"].astype(str) == "status", "value"]
    if len(status_values) != 1 or pd.isna(status_values.iloc[0]):
        return "not_evaluable", f"{module_name}_summary_status_invalid"
    try:
        status = validate_module_state(str(status_values.iloc[0]).strip())
    except ValueError:
        return "not_evaluable", f"{module_name}_summary_status_invalid"

    reason_values = frame.loc[frame["metric"].astype(str) == "reason_code", "value"]
    reason = ""
    if len(reason_values) == 1 and not pd.isna(reason_values.iloc[0]):
        reason = str(reason_values.iloc[0]).strip()
    if status != "ok" and not reason:
        reason = f"{module_name}_status_{status}"
    return status, reason
