#!/usr/bin/env python3
"""Build the lead report-native public ONT example figure.

The historical output filename is retained for README/manuscript compatibility,
but this figure intentionally contains no workflow schematic.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.image as mpimg
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch


ROOT = Path(__file__).resolve().parents[1]
FIGURE_DIR = ROOT / "paper" / "figures"
SOURCE_DIR = ROOT / "examples" / "public_validation" / "GM12878_ONT_longread" / "figures"
OUT_PNG = FIGURE_DIR / "figure0_workflow_architecture.png"
OUT_SVG = FIGURE_DIR / "figure0_workflow_architecture.svg"

TEXT = "#17212b"
MUTED = "#536276"
FRAME = "#cfd9e5"
CARD = "#f8fafc"

PANELS = [
    ("A", "Mitochondrial depth profile", "mito_depth_profile.png"),
    ("B", "Alternate-allele fraction landscape", "mito_heteroplasmy_landscape.png"),
    ("C", "Selected-site read co-occurrence", "mito_cosegregation_heatmap.png"),
    ("D", "Mitochondrial alignment span-versus-MAPQ QC", "mito_numt_qc_mapq_vs_span.png"),
]


def add_panel(fig, rect: tuple[float, float, float, float], panel_id: str, title: str, filename: str) -> None:
    x, y, w, h = rect
    path = SOURCE_DIR / filename
    if not path.exists():
        raise FileNotFoundError(f"Missing required panel image: {path}")

    fig.text(
        x,
        y + h + 0.018,
        f"{panel_id}. {title}",
        ha="left",
        va="bottom",
        fontsize=13.2,
        fontweight="bold",
        color=TEXT,
    )
    card = FancyBboxPatch(
        (x, y),
        w,
        h,
        boxstyle="round,pad=0.004,rounding_size=0.006",
        transform=fig.transFigure,
        linewidth=1.1,
        edgecolor=FRAME,
        facecolor="white",
        zorder=1,
    )
    fig.patches.append(card)

    ax = fig.add_axes((x + 0.015, y + 0.018, w - 0.030, h - 0.036), zorder=2)
    ax.imshow(mpimg.imread(path))
    ax.axis("off")


def build_figure() -> None:
    FIGURE_DIR.mkdir(parents=True, exist_ok=True)
    plt.rcParams.update(
        {
            "font.family": "DejaVu Sans",
            "svg.fonttype": "none",
            "svg.hashsalt": "mito-overview",
        }
    )

    fig = plt.figure(figsize=(15.5, 10.0), dpi=200, facecolor="white")
    title = "Public ONT long-read report-native views"
    subtitle = (
        "Representative GM12878 targeted-mt output panels generated by mito-overview; "
        "shown as generated outputs, not analytical performance benchmarks."
    )
    fig.text(0.045, 0.955, title, ha="left", va="top", fontsize=20, fontweight="bold", color=TEXT)
    fig.text(0.045, 0.918, subtitle, ha="left", va="top", fontsize=10.5, color=MUTED)

    # Subtle title-band background keeps the montage readable in GitHub previews.
    band = FancyBboxPatch(
        (0.035, 0.870),
        0.930,
        0.105,
        boxstyle="round,pad=0.008,rounding_size=0.010",
        transform=fig.transFigure,
        linewidth=0,
        facecolor=CARD,
        zorder=0,
    )
    fig.patches.append(band)

    rects = [
        (0.055, 0.525, 0.415, 0.280),
        (0.535, 0.525, 0.415, 0.280),
        (0.095, 0.115, 0.345, 0.315),
        (0.570, 0.115, 0.345, 0.315),
    ]
    if len(rects) != len(PANELS):
        raise ValueError("Panel definitions and layout rectangles must have equal lengths")
    for rect, panel in zip(rects, PANELS):
        add_panel(fig, rect, *panel)

    fig.text(
        0.055,
        0.045,
        "Figure scope: public proof-of-principle report views only. Candidate sites are not independently validated heteroplasmies; alignment QC is not formal NUMT classification.",
        ha="left",
        va="bottom",
        fontsize=9.2,
        color=MUTED,
    )

    fig.savefig(OUT_PNG, dpi=200, facecolor="white")
    fig.savefig(
        OUT_SVG,
        facecolor="white",
        metadata={"Date": None, "Creator": "mito-overview"},
    )
    plt.close(fig)

    # Matplotlib emits trailing spaces in SVG path data; normalize the tracked
    # artifact so regeneration remains compatible with `git diff --check`.
    svg_text = OUT_SVG.read_text(encoding="utf-8")
    OUT_SVG.write_text(
        "\n".join(line.rstrip() for line in svg_text.splitlines()) + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    build_figure()
